adapterConfig:
  create: true
  files:
    adapterconfig.yaml: examples/example2-job/adapterconfig.yaml
    job.yaml : examples/example2-job/job.yaml

log:
  level: debug

broker:
  create: true
  googlepubsub:
    projectId: CHANGE_ME
    subscriptionId: CHANGE_ME
    topic: CHANGE_ME
    deadLetterTopic: CHANGE_ME

image:
  repository: hyperfleet-adapter
  pullPolicy: Always
  tag: latest

env:
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: SERVICE_ACCOUNT
    valueFrom:
      fieldRef:
        fieldPath: spec.serviceAccountName
  - name: SIMULATE_RESULT
    value: success     # other possible values: success, failure, hang, crash, invalid-json, missing-status

rbac:
   resources:
     - namespaces
     - serviceaccounts
     - configmaps
     - jobs
     - roles
     - rolebindings
