{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hyperfleet-adapter.fullname" . }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
rules:
{{- range .Values.rbac.resources }}
  - apiGroups: ["{{ include "hyperfleet-adapter.apiGroup" . }}"]
    resources: ["{{ . }}"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
{{- with .Values.rbac.rules }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hyperfleet-adapter.fullname" . }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hyperfleet-adapter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hyperfleet-adapter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
