apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .clusterId }}"
  labels:
    hyperfleet.io/cluster-id: "{{ .clusterId }}"
    hyperfleet.io/cluster-name: "{{ .clusterName }}"
  annotations:
    hyperfleet.io/generation: "{{ .generationId }}"
