apiVersion: v2
name: hyperfleet-adapter
description: HyperFleet Adapter - Event-driven adapter services for HyperFleet cluster provisioning
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: HyperFleet Team
    email: hyperfleet-team@redhat.com
keywords:
  - hyperfleet
  - adapter
  - cloudevents
  - kubernetes
home: https://github.com/openshift-hyperfleet/hyperfleet-adapter

