adapterConfig:
  create: true
  files:
    adapterconfig.yaml: examples/example3-deployment/adapterconfig.yaml
    deployment.yaml : examples/example3-deployment/deployment.yaml

log:
  level: debug

broker:
  create: true
  googlepubsub:
    projectId: CHANGE_ME
    subscriptionId: CHANGE_ME
    topic: CHANGE_ME
    deadLetterTopic: CHANGE_ME

image:
  registry: CHANGE_ME
  repository: hyperfleet-adapter
  pullPolicy: Always
  tag: latest

env:
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: SERVICE_ACCOUNT
    valueFrom:
      fieldRef:
        fieldPath: spec.serviceAccountName
  - name: SIMULATE_RESULT
    value: success     # other possible values: success, failure, hang, crash, invalid-json, missing-status
